# Generated by Django 5.2.7 on 2025-10-20 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('folder_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_folders', to=settings.AUTH_USER_MODEL)),
                ('parent_folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='assets.folder')),
            ],
            options={
                'db_table': 'folders',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('asset_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('asset_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document'), ('glb', 'GLB'), ('other', 'Other')], max_length=20)),
                ('file_path', models.CharField(max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_assets', to=settings.AUTH_USER_MODEL)),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='assets.folder')),
            ],
            options={
                'db_table': 'assets',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='MetadataField',
            fields=[
                ('field_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('data_type', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('date', 'Date'), ('boolean', 'Boolean'), ('float', 'Float')], max_length=20)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_metadata_fields', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'metadata_fields',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('version_id', models.AutoField(primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('file_path', models.CharField(max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('changes_note', models.TextField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='assets.asset')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'versions',
                'ordering': ['-asset_id', '-version_number'],
                'unique_together': {('asset', 'version_number')},
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_for_assets', to='assets.version'),
        ),
        migrations.CreateModel(
            name='AssetMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='assets.asset')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_values', to='assets.metadatafield')),
            ],
            options={
                'db_table': 'asset_metadata',
                'indexes': [models.Index(fields=['field'], name='asset_metad_field_i_19ef74_idx'), models.Index(fields=['asset'], name='asset_metad_asset_i_247891_idx')],
                'unique_together': {('asset', 'field')},
            },
        ),
        migrations.CreateModel(
            name='AssetTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_tags', to='assets.asset')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_assets', to='assets.tag')),
            ],
            options={
                'db_table': 'asset_tags',
                'indexes': [models.Index(fields=['tag'], name='asset_tags_tag_id_7c841d_idx'), models.Index(fields=['asset'], name='asset_tags_asset_i_900a88_idx')],
                'unique_together': {('asset', 'tag')},
            },
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['name'], name='assets_name_74a4a9_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['asset_type'], name='assets_asset_t_fc4c39_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['uploaded_at'], name='assets_uploade_6dfe1e_idx'),
        ),
    ]
