# Generated by Django 5.2.7 on 2025-10-20 20:20

import assets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='upload_file',
            field=models.FileField(blank=True, null=True, upload_to=assets.models.asset_upload_path),
        ),
        migrations.AddField(
            model_name='version',
            name='upload_file',
            field=models.FileField(blank=True, null=True, upload_to=assets.models.version_upload_path),
        ),
    ]
