# Generated by Django 5.2.7 on 2025-10-30 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_asset_upload_file_version_upload_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
