# Generated by Django 5.2.6 on 2025-11-01 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_version_snapshot'),
        ('assets', '0003_version_snapshot_version_versions_snapshot_gin_idx'),
    ]

    operations = [
    ]
