# Generated by Django 5.2.6 on 2025-11-01 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_merge_20251101_1323'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='version',
            name='versions_snapshot_gin_idx',
        ),
    ]
