# Generated by Django 5.2.7 on 2025-11-03 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_remove_version_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
