# Generated by Django 5.2.7 on 2025-11-03 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_version_snapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folder_mappings', to='assets.asset')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_mappings', to='assets.folder')),
            ],
            options={
                'db_table': 'asset_folders',
                'indexes': [models.Index(fields=['asset'], name='asset_folde_asset_i_1312d6_idx'), models.Index(fields=['folder'], name='asset_folde_folder__8d84ef_idx')],
                'unique_together': {('asset', 'folder')},
            },
        ),
    ]
