# Generated by Django 5.2.7 on 2025-11-03 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_assetfolder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='folder',
        ),
    ]
