# Generated by Django 5.2.7 on 2025-11-03 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_remove_asset_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='assets.folder'),
        ),
    ]
