# Generated by Django 5.2.7 on 2025-11-06 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_merge_20251102_1519'),
        ('assets', '0010_asset_folder'),
    ]

    operations = [
    ]
